(function(){
'use strict';
var categories={market:{en:'Wet / Fresh Market',zh:'菜市场 / 鲜货市场',icon:'🥬'},grocery:{en:'Supermarket / Grocery',zh:'超市 / 杂货',icon:'🛒'},chinese:{en:'Chinese Grocery',zh:'中国超市',icon:'🥟'},school:{en:'School / University',zh:'学校 / 大学',icon:'🎓'},transit:{en:'LRT / MRT / Transport',zh:'交通',icon:'🚆'},food:{en:'Food / Restaurant',zh:'餐饮',icon:'🍜'},medical:{en:'Medical',zh:'医疗',icon:'🏥'},shopping:{en:'Shopping',zh:'购物',icon:'🛍️'},leisure:{en:'Leisure / Park',zh:'休闲 / 公园',icon:'🌳'},other:{en:'Other',zh:'其他',icon:'📍'}};
var state={version:1,title:'',client:'',home:{name:'',address:'',lat:null,lng:null},intro:'',pois:[]};
var lang='en',markerHome=null,poiMarkers=[],map;var $=function(id){return document.getElementById(id)};
function initMap(){map=L.map('map',{zoomControl:true}).setView([3.139,101.6869],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map)}
function fillCategories(){var s=$('poiCategory');Object.keys(categories).forEach(function(k){var o=document.createElement('option');o.value=k;o.textContent=categories[k].icon+' '+categories[k].en;s.appendChild(o)})}
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]})}
function gmapsUrl(p){return 'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent((p.name?p.name+' ':'')+(p.address||''))}
function hav(a,b){if(!a||!b||a.lat==null||b.lat==null)return null;var R=6371,dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)*Math.sin(dLat/2)+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)*Math.sin(dLng/2);return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function distanceText(p){var d=hav(state.home,p);if(d==null)return '';return d<1?Math.round(d*1000)+' m':d.toFixed(1)+' km'}
function homeIcon(){return L.divIcon({className:'leaflet-div-icon',html:'<div class="home-pin">⌂</div>',iconSize:[36,36],iconAnchor:[18,18]})}
function poiIcon(cat){var c=categories[cat]||categories.other;return L.divIcon({className:'leaflet-div-icon',html:'<div class="poi-pin">'+c.icon+'</div>',iconSize:[32,32],iconAnchor:[16,16]})}
function setStatus(id,msg,cls){var e=$(id);e.textContent=msg||'';e.className='status'+(cls?' '+cls:'')}
async function geocode(q){var url='https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=my&q='+encodeURIComponent(q);var r=await fetch(url,{headers:{'Accept':'application/json'}});if(!r.ok)throw new Error('Location search unavailable');var a=await r.json();if(!a.length)throw new Error('Place not found. Try a fuller address.');return {lat:parseFloat(a[0].lat),lng:parseFloat(a[0].lon),display:a[0].display_name}}
function syncFromForm(){state.title=$('mapTitle').value.trim();state.client=$('clientName').value.trim();state.home.name=$('homeName').value.trim();state.home.address=$('homeAddress').value.trim();state.intro=$('intro').value.trim();saveDraft()}
function syncToForm(){$('mapTitle').value=state.title||'';$('clientName').value=state.client||'';$('homeName').value=state.home.name||'';$('homeAddress').value=state.home.address||'';$('intro').value=state.intro||''}
function saveDraft(){try{localStorage.setItem('propertySpotMapDraft',JSON.stringify(state))}catch(e){}}
function loadDraft(){try{var x=localStorage.getItem('propertySpotMapDraft');if(x){var d=JSON.parse(x);if(d&&d.home)state=d}}catch(e){}}
function renderMap(fit){if(markerHome){map.removeLayer(markerHome);markerHome=null}poiMarkers.forEach(function(m){map.removeLayer(m)});poiMarkers=[];var pts=[];if(state.home.lat!=null){markerHome=L.marker([state.home.lat,state.home.lng],{icon:homeIcon()}).addTo(map).bindPopup('<div class="popupTitle">'+esc(state.home.name||'Property')+'</div><div class="popupMeta">'+esc(state.home.address)+'</div><a class="popupLink" target="_blank" rel="noopener" href="'+gmapsUrl(state.home)+'">Open in Google Maps ↗</a>');pts.push([state.home.lat,state.home.lng])}state.pois.forEach(function(p,i){if(p.lat==null)return;var c=categories[p.category]||categories.other;var m=L.marker([p.lat,p.lng],{icon:poiIcon(p.category)}).addTo(map).bindPopup('<div class="popupTitle">'+c.icon+' '+esc(p.name)+'</div><div class="popupMeta">'+esc(p.address)+'</div>'+(p.note?'<div class="popupMeta" style="margin-top:5px">'+esc(p.note)+'</div>':'')+'<a class="popupLink" target="_blank" rel="noopener" href="'+gmapsUrl(p)+'">Open in Google Maps ↗</a>');m._poiIndex=i;poiMarkers.push(m);pts.push([p.lat,p.lng])});if(fit&&pts.length){if(pts.length===1)map.setView(pts[0],15);else map.fitBounds(pts,{padding:[48,48],maxZoom:15})}}
function renderEditorList(){var el=$('poiEditList');el.innerHTML='';if(!state.pois.length){el.innerHTML='<div class="empty">No places added yet.</div>';return}state.pois.forEach(function(p,i){var c=categories[p.category]||categories.other;var d=document.createElement('div');d.className='poiEdit';d.innerHTML='<div class="poiIcon">'+c.icon+'</div><div><div class="poiTitle">'+esc(p.name)+'</div><div class="poiMeta">'+esc(c.en)+' · '+esc(distanceText(p))+'</div><div class="poiMeta">'+esc(p.address)+'</div>'+(p.note?'<div class="poiMeta">'+esc(p.note)+'</div>':'')+'</div><div class="row"><button class="btn tiny ghost" data-focus="'+i+'">Map</button><button class="btn tiny ghost danger" data-delete="'+i+'">×</button></div>';el.appendChild(d)});el.querySelectorAll('[data-delete]').forEach(function(b){b.onclick=function(){state.pois.splice(+b.dataset.delete,1);saveDraft();renderAll(true)}});el.querySelectorAll('[data-focus]').forEach(function(b){b.onclick=function(){focusPoi(+b.dataset.focus)}})}
function renderClient(){var t=state.title||state.home.name||'Property Spot Map';$('clientTopTitle').textContent=t;$('clientTopRef').textContent=state.client?((lang==='zh'?'客户 / 参考：':'Client / ref: ')+state.client):'';$('clientHomeName').textContent=state.home.name||(lang==='zh'?'物业':'Property');$('clientHomeAddress').textContent=state.home.address||'';$('clientIntro').textContent=state.intro||'';$('clientCount').textContent=state.pois.length+(lang==='zh'?' 个地点':' places');var list=$('clientPoiList');list.innerHTML='';if(!state.pois.length){list.innerHTML='<div class="empty">'+(lang==='zh'?'暂时没有加入附近地点。':'No nearby places added yet.')+'</div>';return}var sorted=state.pois.map(function(p,i){return {p:p,i:i,d:hav(state.home,p)}}).sort(function(a,b){return (a.d==null?999:a.d)-(b.d==null?999:b.d)});sorted.forEach(function(x){var p=x.p,c=categories[p.category]||categories.other,item=document.createElement('div');item.className='clientPoi';item.innerHTML='<div class="poiIcon">'+c.icon+'</div><div><div class="poiTitle">'+esc(p.name)+'</div><div class="poiMeta">'+esc(lang==='zh'?c.zh:c.en)+(distanceText(p)?' · '+esc(distanceText(p)):'')+'</div>'+(p.note?'<div class="note">'+esc(p.note)+'</div>':'')+'</div><a class="gmaps" target="_blank" rel="noopener" href="'+gmapsUrl(p)+'">Google Maps ↗</a>';item.onclick=function(e){if(e.target.tagName.toLowerCase()==='a')return;focusPoi(x.i)};list.appendChild(item)});$('langBtn').textContent=lang==='en'?'中文':'EN'}
function renderAll(fit){syncToForm();renderEditorList();renderMap(fit);renderClient()}
function focusPoi(i){var p=state.pois[i];if(!p||p.lat==null)return;map.setView([p.lat,p.lng],16);var m=poiMarkers.find(function(x){return x._poiIndex===i});if(m)m.openPopup()}
async function setHome(){syncFromForm();var q=(state.home.name?state.home.name+' ':'')+state.home.address;if(!q.trim()){setStatus('homeStatus','Enter the property name or address.','warn');return}var b=$('setHomeBtn');b.disabled=true;setStatus('homeStatus','Finding property…');try{var g=await geocode(q);state.home.lat=g.lat;state.home.lng=g.lng;saveDraft();renderAll(true);setStatus('homeStatus','Property pinned.','ok')}catch(e){setStatus('homeStatus',e.message,'warn')}finally{b.disabled=false}}
async function addPoi(){syncFromForm();var p={category:$('poiCategory').value,name:$('poiName').value.trim(),address:$('poiAddress').value.trim(),note:$('poiNote').value.trim(),lat:null,lng:null};if(!p.name&&!p.address){setStatus('poiStatus','Enter a place name or address.','warn');return}var b=$('addPoiBtn');b.disabled=true;setStatus('poiStatus','Finding place…');try{var g=await geocode((p.name?p.name+' ':'')+p.address);p.lat=g.lat;p.lng=g.lng;state.pois.push(p);saveDraft();clearPoi();renderAll(true);setStatus('poiStatus','Added to map.','ok')}catch(e){setStatus('poiStatus',e.message,'warn')}finally{b.disabled=false}}
function clearPoi(){$('poiName').value='';$('poiAddress').value='';$('poiNote').value='';setStatus('poiStatus','')}
function bytesToB64Url(bytes){var s='';bytes.forEach(function(b){s+=String.fromCharCode(b)});return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64UrlToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';var bin=atob(s),a=new Uint8Array(bin.length);for(var i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function encodeState(){syncFromForm();return bytesToB64Url(new TextEncoder().encode(JSON.stringify(state)))}
function decodeState(s){return JSON.parse(new TextDecoder().decode(b64UrlToBytes(s)))}
function makeUrls(){var hash=encodeState(),base=location.origin+location.pathname;return {client:base+'#'+hash,edit:base+'?edit=1#'+hash}}
function openShare(){if(state.home.lat==null){setStatus('homeStatus','Set the main property first.','warn');return}var u=makeUrls();$('clientUrlBox').textContent=u.client;$('editUrlBox').textContent=u.edit;$('shareModal').classList.add('open')}
function copyText(t){if(navigator.clipboard&&window.isSecureContext)return navigator.clipboard.writeText(t);var x=document.createElement('textarea');x.value=t;document.body.appendChild(x);x.select();document.execCommand('copy');x.remove();return Promise.resolve()}
function downloadJson(){syncFromForm();var blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=((state.home.name||'property-map').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'').toLowerCase()||'property-map')+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href)},1000)}
function importJson(file){var r=new FileReader();r.onload=function(){try{var d=JSON.parse(r.result);if(!d.home||!Array.isArray(d.pois))throw new Error();state=d;saveDraft();renderAll(true);setStatus('homeStatus','Map imported.','ok')}catch(e){setStatus('homeStatus','Invalid map JSON.','warn')}};r.readAsText(file)}
function newMap(){if(!confirm('Start a new map? Your current draft will be cleared from this browser.'))return;state={version:1,title:'',client:'',home:{name:'',address:'',lat:null,lng:null},intro:'',pois:[]};localStorage.removeItem('propertySpotMapDraft');history.replaceState(null,'',location.pathname+'?edit=1');renderAll(false);map.setView([3.139,101.6869],12)}
async function loadDemo(){state={version:1,title:'Impian Villas — 买菜 & Daily Convenience',client:'China family',home:{name:'Impian Villas',address:'Jalan Kiara 3, Mont Kiara, 50480 Kuala Lumpur',lat:null,lng:null},intro:'For daily cooking and groceries, there are both convenient supermarkets and traditional fresh markets within a short drive. 点击地点可在地图查看，Google Maps 按钮可直接导航。',pois:[]};syncToForm();setStatus('homeStatus','Building demo map…');var items=[{category:'market',name:'Kepong Baru Morning Market',address:'55 Lorong Bangau 2, Kepong Baru, 52100 Kuala Lumpur',note:'Traditional wet market / 早市 — vegetables, meat, fish and everyday fresh produce.'},{category:'market',name:'ShunYuan Fresh Market',address:'12 Jalan Lang Kuning, Taman Sri Sinar, 52100 Kuala Lumpur',note:'Fresh produce market; useful for everyday vegetables and seafood.'},{category:'grocery',name:'Jaya Grocer @ 163 Retail Park',address:'163 Retail Park, Jalan Kiara, Mont Kiara, Kuala Lumpur',note:'Convenient supermarket option in Mont Kiara.'},{category:'market',name:'Pasar Besar TTDI',address:'Taman Tun Dr Ismail Wet Market, Kuala Lumpur',note:'Traditional wet market with fresh vegetables, fish and meat.'},{category:'chinese',name:'Wishmart Chinese Supermarket',address:'Bandar Menjalara, 52200 Kuala Lumpur',note:'Useful for China-brand groceries and familiar cooking ingredients.'}];try{var gh=await geocode(state.home.name+' '+state.home.address);state.home.lat=gh.lat;state.home.lng=gh.lng;for(var i=0;i<items.length;i++){setStatus('homeStatus','Finding demo places '+(i+1)+'/'+items.length+'…');try{var g=await geocode(items[i].name+' '+items[i].address);items[i].lat=g.lat;items[i].lng=g.lng;state.pois.push(items[i])}catch(e){items[i].lat=null;items[i].lng=null;state.pois.push(items[i])}if(i<items.length-1)await new Promise(function(res){setTimeout(res,1100)})}saveDraft();renderAll(true);setStatus('homeStatus','Impian Villas demo loaded.','ok')}catch(e){saveDraft();renderAll(false);setStatus('homeStatus','Demo loaded, but automatic location lookup was unavailable. You can still edit it.','warn')}}
function boot(){fillCategories();initMap();var hasHash=location.hash.length>1,edit=new URLSearchParams(location.search).get('edit')==='1';if(hasHash){try{state=decodeState(location.hash.slice(1))}catch(e){loadDraft()}}else loadDraft();var readOnly=hasHash&&!edit;if(readOnly){$('app').classList.add('readOnly');$('modeLabel').textContent='Client view'}else{$('modeLabel').textContent='Agent builder'}renderAll(true);$('setHomeBtn').onclick=setHome;$('addPoiBtn').onclick=addPoi;$('clearPoiBtn').onclick=clearPoi;$('shareBtn').onclick=openShare;$('exportBtn').onclick=downloadJson;$('newBtn').onclick=newMap;$('demoBtn').onclick=loadDemo;['mapTitle','clientName','homeName','homeAddress','intro'].forEach(function(id){$(id).addEventListener('input',function(){syncFromForm();renderClient()})});$('importFile').onchange=function(){if(this.files&&this.files[0])importJson(this.files[0]);this.value=''};$('closeShareBtn').onclick=function(){$('shareModal').classList.remove('open')};$('shareModal').onclick=function(e){if(e.target===$('shareModal'))$('shareModal').classList.remove('open')};document.querySelectorAll('[data-copy]').forEach(function(b){b.onclick=function(){var u=makeUrls();copyText(u[b.dataset.copy]).then(function(){var old=b.textContent;b.textContent='Copied';setTimeout(function(){b.textContent=old},1200)})}});document.querySelectorAll('[data-open]').forEach(function(b){b.onclick=function(){var u=makeUrls();window.open(u[b.dataset.open],'_blank','noopener')}});$('copyClientUrlBtn').onclick=function(){copyText(location.href).then(function(){var b=$('copyClientUrlBtn'),old=b.textContent;b.textContent=lang==='zh'?'已复制':'Copied';setTimeout(function(){b.textContent=old},1200)})};$('langBtn').onclick=function(){lang=lang==='en'?'zh':'en';renderClient()};setTimeout(function(){map.invalidateSize();renderMap(true)},150)}
boot();
})();